services:
  db:
    image: mysql:8.0
    restart: "no"
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --max-allowed-packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - challenge.local
  wp:
    depends_on:
      - db
    image: wordpress
    restart: "no"
    volumes:
      - ".:/var/www/html/wp-content/plugins/creed-cast"
      - "./src/assets:/var/www/html/wp-content/plugins/creed-cast/public"
      - "./public/style.css:/var/www/html/wp-content/plugins/creed-cast/public/style.css"
      - "./wordpress:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: creed_
      PROJECT_PREFIX: creed_
    ports:
      - 80:80
    networks:
      - challenge.local
  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 500M
    networks:
      - challenge.local

networks:
  challenge.local:

volumes:
  data:
